username: foxsin34
picture_url: https://avatars3.githubusercontent.com/u/58812623?s=460&u=5fc6f13f70f78d9e7d50f1ef937ef1dd7fe28d2b&v=4
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My first Blog and enjoy.
paginate: 7
paginate_path: "/blog/page:num/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
